version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    container_name: mongo-service
    ports:
      - 27017:27017
  banca-service:
    image: springboot-mongodb:1.0
    container_name: banca-service-api
    ports:
      - 8080:8080
    depends_on:
      - mongodb
